### ISSUE TITLE
注册服务里面的方法为Task方法，并且Task无返回值时会出现调用异常

### ISSUE THREAD

**Issue by szzProject** [hprose/hprose-dotnet#53]
异常：Unable to cast object of type 'Hprose.IO.Deserializers.CharsDeserializer' to type 'Hprose.IO.Deserializers.IObjectDeserializer'
注册服务方法示例：
public class TestServer:ITestServer
{
      public async Task Test(string input)
      {
             ......;
       }
}

调用示例：
public async Task Test(string input)
{
    var server = _client.UseService<ITestServer>();
    await server.Test(input);
}
调用客户端采用接口调用方式，调用方法已经正确执行，但是RPC客户端会返回异常信息。
例外：如果调用的Task方法有返回值，则可以调用成功，如：
public async Task《string》 Test(string input)
经过进一步测试发现，如果调用的时候不加await则不会出现异常，希望能给与一定的指导

**Comment by szzProject** [comment]
你好，我自己做了一个简单的调用示例程序，发现异常信息不一样了，但是await执行的时候还是会出现异常
异常：System.Collections.Generic.KeyNotFoundException: The given key '' was not present in the dictionary.
异常堆栈：
   at System.ThrowHelper.ThrowKeyNotFoundException[T](T key)
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at Hprose.IO.MembersReader.CreateReadBlock(Dictionary`2 members, String[] names, ParameterExpression reader, ParameterExpression obj)
   at Hprose.IO.MembersReader.CreateReadAction[T](Dictionary`2 members, String[] names)
   at Hprose.IO.MembersReader`1.<>c__DisplayClass6_0.<.cctor>b__2()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at Hprose.IO.MembersReader`1.ReadAllMembers(Reader reader, String key, T& obj)
   at Hprose.IO.Deserializers.StructDeserializer`1.Read(Reader reader, String key)
   at Hprose.IO.Deserializers.StructDeserializer`1.ReadObject(Reader reader, String key)
   at Hprose.IO.Deserializer`1.Read(Reader reader, Int32 tag)
   at Hprose.IO.Deserializer`1.Hprose.IO.IDeserializer.Deserialize(Reader reader)
   at Hprose.RPC.ClientCodec.<Decode>d__32.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Hprose.RPC.Client.<Call>d__52.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Hprose.RPC.Client.<InvokeAsync>d__51`1.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at RPCTest.Program.<Main>d__1.MoveNext() in E:\Github\RPCTest\Program.cs:line 29

**Comment by andot** [comment]
看上去像是服务器返回的对象没有返回字段。
