### ISSUE TITLE
请问一下自定义对象结果返回报错问题

### ISSUE THREAD

**Issue by zgqhuolang** [hprose/hprose-dotnet#78]
var client = new Client("tcp://127.0.0.1:8889");
client.RequestHeaders.Add("token", "djfalkdsjfgldsfad");
TypeManager.Register<ExamMember>("ExamMember");
IHello hello = client.UseService<IHello>(); 
var x = hello.GetStuExamInfoList2();         
Console.WriteLine(JsonConvert.SerializeObject(x));

请求的服务器数据返回有数据  但是有异常！
Unhandled exception. System.InvalidCastException: Cannot convert System.Char[] to ConsoleApp1.ExamMember.
   at Hprose.IO.Deserializers.ObjectDeserializer`1.Read(Reader reader)
   at Hprose.IO.Deserializers.ObjectDeserializer`1.Read(Reader reader, Int32 tag)
   at Hprose.IO.Deserializer`1.Deserialize(Reader reader)
   at Hprose.IO.Deserializer`1.Read(Reader reader, Int32 tag)
   at Hprose.IO.Deserializers.ObjectDeserializer`1.Read(Reader reader, Int32 tag)
   at Hprose.IO.Deserializer`1.Deserialize(Reader reader)
   at Hprose.IO.Deserializer`1.Hprose.IO.IDeserializer.Deserialize(Reader reader)
   at Hprose.RPC.ClientCodec.Decode(MemoryStream response, ClientContext context)
   at Hprose.RPC.Client.Call(String name, Object[] args, Context context)
   at Hprose.RPC.Client.InvokeAsync[T](String name, Object[] args, ClientContext context)
   at Hprose.RPC.Client.Invoke[T](String name, Object[] args, ClientContext context)
   at Hprose.RPC.SyncInvoker`1.Invoke(Object[] args)
   at Hprose.RPC.InvocationHandler.Invoke(Object proxy, MethodInfo method, Object[] args)
   at $Proxy0.IHello.GetStuExamInfoList2()

自定义类这块要怎么使用呢？
求助！！！！

**Comment by andot** [comment]
升级到最新版本就可以了。

**Comment by zgqhuolang** [comment]
我是直接用nuget上最新的3.0.18   现在我用的下载的源码编译的dll来测试 
![image](https://user-images.githubusercontent.com/55520394/104875563-8b2bd380-5990-11eb-96bf-ea7b45c50d08.png)
就是报空引用了    at Hprose.IO.Deserializers.ObjectDeserializer`1.Read(Reader reader) in E:\hprose-dotnet-master\src\Hprose.IO\Deserializers\ObjectDeserializer.cs:line 43

**Comment by andot** [comment]
新的 Hprose.IO 这个库的版本是 3.0.19

**Comment by andot** [comment]
空引用是说你的那个类，没有注册。你用 TypeManager.Register 注册一下你要传输的那个类就可以了。

**Comment by zgqhuolang** [comment]
谢谢 之前命名空间没用对 我用 TypeManager.Register 注册重试了一下  可以了  
但是 有没有一种就是根据属性自动映射的方法呢？就是服务端和客户端不是通用的一个实体 但是属性基本一致这种

**Comment by andot** [comment]
可以，客户端和服务器把不同的两个类注册成同一个名字就行。

**Comment by zgqhuolang** [comment]
你说的是TypeManager.Register<ExamMember>("ExamMember");这样么？   事实上我需要TypeManager.Register<E_ExamMember>("Server_Models_Entites_exam_E_ExamMember");这样才能正常拿到数据  就是需要用服务器端的实体的完整的命名空间才行 不知道是不是我用错了   总感觉这种用法不太科学 哈哈

**Comment by andot** [comment]
我是说客户端：`TypeManager.Register<ExamMember>("ExamMember");`，服务器：`TypeManager.Register<E_ExamMember>("ExamMember");`，这样它们就会被认为是同一个类。当然你客户端和服务器需要在两台不同的机器上。

**Comment by zgqhuolang** [comment]
可以了  非常感谢！！
